import {
  Box,
  Typography,
  styled,
  Grid,
  Button,
  Container,
} from "@mui/material";

import Head from "next/head";
import Header from "../components/Header/Header";
import Review from "../components/Review";

import Slider from "../components/SliderItem/SliderItem";

import { Swiper, SwiperSlide } from "swiper/react";
import { Navigation, FreeMode, Thumbs, Autoplay } from "swiper";

import "swiper/css";
import "swiper/css/navigation";
import HighQuality from "../components/HighQuality";

import { ToastContainer } from "react-toastify";
import Item from "../components/Item/Item";

export default function Home({ data, reviews }) {
  const StyledSection = styled(Box)({
    display: "flex",
    flexDirection: "column",
    gap: "10px",
    margin: "100px 0",
    textAlign: "center",
  });

  const data1 = data.slice(0, 4);
  const data2 = data.slice(4, 8);

  return (
    <div>
      <Head>
        <title>Virtua</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header />

      <Box sx={{ marginTop: { xs: "56px", md: "72px" }, position: "relative" }}>
        <Slider />

        <Box
          component="img"
          alt="The house from the offer."
          src="./assets/img/hight-light.png"
          sx={{
            position: "absolute",
            bottom: "-1px",
            zIndex: 1,
            display: { xs: "none", md: "block" },
          }}
        ></Box>
      </Box>

      {/* Hight Quality VR */}
      <Container>
        <StyledSection>
          <Typography sx={{ fontSize: "18px", fontWeight: "100" }}>
            High-Quality VR
          </Typography>
          <Typography
            sx={{
              fontSize: "30px",
              fontWeight: "700",
              fontFamily: "'Kodchasan', sans-serif",
            }}
          >
            The Real World Immersion
          </Typography>
          <Box
            sx={{
              display: "block",
              bgcolor: "#d23369",
              width: "50px",
              height: "3px",
              margin: "auto",
            }}
          ></Box>
          <Box>
            <HighQuality data={data} />
            {/* <Swiper
              loop={true}
              autoplay={{
                delay: 10000,
                disableOnInteraction: false,
              }}
              slidesPerGroup={1}
              slidesPerView={1}
              modules={[Autoplay]}
            >
              <SwiperSlide>
                <Grid container>
                  {data1.map((item) => (
                    <Grid item xs={12} md={3}>
                      <Item product={item} />
                    </Grid>
                  ))}
                </Grid>
              </SwiperSlide>
              <SwiperSlide>
                <Grid container>
                  {data2.map((item) => (
                    <Grid item xs={12} md={3}>
                      <Item product={item} />
                    </Grid>
                  ))}
                </Grid>
              </SwiperSlide>
            </Swiper> */}
          </Box>
        </StyledSection>

        {/* About Project */}
        <Box>
          <Grid container bgcolor="#fff1f5">
            <Grid item xs={12} md={5}>
              <Box
                sx={{
                  backgroundImage: `url(./assets/img/about-hero.png)`,
                  minHeight: "400px",
                  height: "100%",
                  backgroundSize: "cover",
                  backgroundPosition: "center",
                  transition: "opacity ease-in-out 0.3s",
                  "&:hover": {
                    opacity: "0.7",
                  },
                }}
              />
            </Grid>
            <Grid item xs={12} md={7}>
              <Box sx={{ padding: "50px" }}>
                <Typography
                  sx={{ fontSize: "18px", fontWeight: "100" }}
                  mb="25px"
                >
                  About the Project
                </Typography>
                <Typography
                  sx={{
                    fontSize: "60px",
                    fontWeight: "700",
                    fontFamily: "'Kodchasan', sans-serif",
                    lineHeight: 1,
                    marginBottom: "35px",
                  }}
                >
                  Reach out & let your mind explore
                </Typography>
                <Box
                  sx={{
                    display: "block",
                    bgcolor: "#d23369",
                    width: "60px",
                    height: "5px",
                    marginBottom: "35px",
                  }}
                ></Box>
                <Typography
                  sx={{
                    fontSize: "18px",
                    fontWeight: "100",
                    marginBottom: "35px",
                  }}
                >
                  Immerse yourself in an incredible new worlds, find yourself in
                  the center of fascinating universe and try out a new way to
                  play with immerse yourself in an incredible new worlds.
                </Typography>
                <Button variant="contained">Explore More</Button>
              </Box>
            </Grid>
          </Grid>
        </Box>
        {/* Lastest Arrivals */}
        <StyledSection>
          <Typography sx={{ fontSize: "18px", fontWeight: "100" }}>
            Latest Arrivals
          </Typography>
          <Typography
            sx={{
              fontSize: "30px",
              fontWeight: "700",
              fontFamily: "'Kodchasan', sans-serif",
            }}
          >
            VR With Better Perspective
          </Typography>
          <Box
            sx={{
              display: "block",
              bgcolor: "#d23369",
              width: "50px",
              height: "3px",
              margin: "auto",
            }}
          ></Box>
          <Box>
            <Box>
              <HighQuality data={data} />
            </Box>
          </Box>
        </StyledSection>
        {/* Our VR Features */}
        <Box>
          <Grid container bgcolor="#fff1f5">
            <Grid item xs={12} md={7} sx={{ order: { xs: 2, md: 1 } }}>
              <Box sx={{ padding: "50px" }}>
                <Typography
                  sx={{ fontSize: "18px", fontWeight: "100" }}
                  mb="25px"
                >
                  Our VR Features
                </Typography>
                <Typography
                  sx={{
                    fontSize: "60px",
                    fontWeight: "700",
                    fontFamily: "'Kodchasan', sans-serif",
                    lineHeight: 1,
                    marginBottom: "35px",
                  }}
                >
                  New & Better Features
                </Typography>
                <Box
                  sx={{
                    display: "block",
                    bgcolor: "#d23369",
                    width: "60px",
                    height: "5px",
                    margin: "0 0 50px 0",
                  }}
                ></Box>
                <Typography
                  sx={{
                    fontSize: "18px",
                    fontWeight: "100",
                    marginBottom: "35px",
                  }}
                >
                  Donec ipsum neque, tincidunt non auctor at, finibus vitae
                  nunc. Fusce sagittis, tortor sed viverra elementum, odio odio
                  tempus quam, ac imperdiet dui lacus eu magna.
                </Typography>
                <Button variant="contained">Explore More</Button>
              </Box>
            </Grid>
            <Grid item xs={12} md={5} sx={{ order: { xs: 1, md: 2 } }}>
              <Box
                sx={{
                  backgroundImage: `url(./assets/img/about-hero-2.png)`,
                  minHeight: "400px",
                  height: "100%",
                  backgroundSize: "cover",
                  backgroundPosition: "center",
                  transition: "opacity ease-in-out 0.3s",
                  "&:hover": {
                    opacity: "0.7",
                  },
                }}
              />
            </Grid>
          </Grid>
        </Box>
        {/* Our Prestugious */}
        <StyledSection>
          <Typography sx={{ fontSize: "18px", fontWeight: "100" }}>
            Our Prestigious
          </Typography>
          <Typography
            sx={{
              fontSize: "30px",
              fontWeight: "700",
              fontFamily: "'Kodchasan', sans-serif",
            }}
          >
            Partners
          </Typography>
          <Box
            sx={{
              display: "block",
              bgcolor: "#d23369",
              width: "50px",
              height: "3px",
              margin: "0 auto 50px auto",
            }}
          ></Box>
          <Box>
            <Grid container spacing={4}>
              <Grid
                item
                xs={12}
                sm={6}
                md={2}
                sx={{ marginBottom: { sx: "20px", md: "0px" } }}
              >
                <Box component="img" src="./assets/img/partner-01.png"></Box>
              </Grid>
              <Grid
                item
                xs={12}
                sm={6}
                md={2}
                sx={{ marginBottom: { sx: "20px", md: "0px" } }}
              >
                <Box component="img" src="./assets/img/partner-02.png"></Box>
              </Grid>
              <Grid
                item
                xs={12}
                sm={6}
                md={2}
                sx={{ marginBottom: { sx: "20px", md: "0px" } }}
              >
                <Box component="img" src="./assets/img/partner-03.png"></Box>
              </Grid>
              <Grid
                item
                xs={12}
                sm={6}
                md={2}
                sx={{ marginBottom: { sx: "20px", md: "0px" } }}
              >
                <Box component="img" src="./assets/img/partner-04.png"></Box>
              </Grid>
              <Grid
                item
                xs={12}
                sm={6}
                md={2}
                sx={{ marginBottom: { sx: "20px", md: "0px" } }}
              >
                <Box component="img" src="./assets/img/partner-05.png"></Box>
              </Grid>
              <Grid
                item
                xs={12}
                sm={6}
                md={2}
                sx={{ marginBottom: { sx: "20px", md: "0px" } }}
              >
                <Box component="img" src="./assets/img/partner-05.png"></Box>
              </Grid>
            </Grid>
          </Box>
        </StyledSection>
        {/* Testimonial */}
        <StyledSection>
          <Typography sx={{ fontSize: "18px", fontWeight: "100" }}>
            Testimonial
          </Typography>
          <Typography
            sx={{
              fontSize: "30px",
              fontWeight: "700",
              fontFamily: "'Kodchasan', sans-serif",
            }}
          >
            What Clients Says
          </Typography>
          <Box
            sx={{
              display: "block",
              bgcolor: "#d23369",
              width: "50px",
              height: "3px",
              margin: "0 auto 50px auto",
            }}
          ></Box>
          <Box sx={{ padding: "0 " }}>
            <Swiper
              spaceBetween={10}
              slidesPerView={3}
              freeMode={true}
              watchSlidesProgress={true}
              modules={[FreeMode, Navigation, Thumbs]}
              className="mySwiper"
              breakpoints={{
                0: {
                  slidesPerView: 1,
                },
                600: {
                  slidesPerView: 2,
                },
                900: {
                  slidesPerView: 3,
                },
              }}
            >
              {reviews.map((review) => (
                <SwiperSlide key={review.id}>
                  <Review review={review} />
                </SwiperSlide>
              ))}
              {}
            </Swiper>
          </Box>
        </StyledSection>
      </Container>
      <ToastContainer />
    </div>
  );
}

export const getStaticProps = async (context) => {
  const res = await fetch(
    "https://63a8fbcd100b7737b987d5fd.mockapi.io/products"
  );

  const data = await res.json();

  const resReview = await fetch(
    "https://63a8fbcd100b7737b987d5fd.mockapi.io/reviews"
  );

  const reviews = await resReview.json();

  return {
    props: {
      data,
      reviews,
    },
  };
};
